const type = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_PAGE_LOADER: 'SET_PAGE_LOADER',
  SETTINGS_STATUS: 'SETTINGS_STATUS',
  SET_STORE: 'SET_STORE',
  UPDATE_USER: 'UPDATE_USER',
  VEHICLE_LIST: 'VEHICLE_LIST',
  USER_ROUTE_LIST: 'USER_ROUTE_LIST',
  ALL_BOOKING_ROUTES:'ALL_BOOKING_ROUTES',
  SET_SERACHED_ROUTE_INFO: 'SET_SERACHED_ROUTE_INFO'
}

export default type
