const type = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_PAGE_LOADER: 'SET_PAGE_LOADER',
  SETTINGS_STATUS: 'SETTINGS_STATUS',
  SET_STORE: 'SET_STORE',
  UPDATE_USER: 'UPDATE_USER'
}

export default type
